// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8tt_T-v8OBspcodhqnH7qbIp3iWHuvs0',
    appId: '1:409588710066:web:2f760ea6b04eaeadea27ab',
    messagingSenderId: '409588710066',
    projectId: 'scholar-d37f1',
    authDomain: 'scholar-d37f1.firebaseapp.com',
    storageBucket: 'scholar-d37f1.appspot.com',
    measurementId: 'G-RQVQDHFSHP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYk2De-30YkY5KUYsk8FegdO3VbPfQ6bI',
    appId: '1:409588710066:android:52c2f2c405f2dce4ea27ab',
    messagingSenderId: '409588710066',
    projectId: 'scholar-d37f1',
    storageBucket: 'scholar-d37f1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABE7TaNw4khh98bgEvcp1Is9FivP4p5C4',
    appId: '1:409588710066:ios:db3334d3313064f5ea27ab',
    messagingSenderId: '409588710066',
    projectId: 'scholar-d37f1',
    storageBucket: 'scholar-d37f1.appspot.com',
    iosClientId: '409588710066-5ga7fjm0cud8c1tdav5jrfa0i66s2u0m.apps.googleusercontent.com',
    iosBundleId: 'com.example.scholarChat',
  );
}
